### ISSUE TITLE
Victron SmartSolar and BMV 700 on same device

### ISSUE THREAD

**Issue by MrJoki007** [KinDR007/VictronMPPT-ESPHOME#106]
Hello,
im trying to use a victron Smartsolar 100/20 and BMV 700 on the same device.
Im getting the problem, that the nodemcu loses connection to wifi after short amount of time.
Is there a problem in my code or does it not work to connect two victron devices on one esp?

```
substitutions:
  lower_devicename: "victron"
  devicename: "SmartSolar_100_20"
  config_version: "v2021.05.30"
  wifi_fast_connect: "false"
  accuracy: "2"
  mpptname: SmartSolar
  bmvname: BMV

esphome:
  name: victron

esp8266:
  board: nodemcuv2


external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s
  - source: github://KinDR007/VictronSmartShunt-ESPHOME@main
    refresh: 0s

# Enable logging
logger:
  esp8266_store_log_strings_in_flash: false

# Enable Home Assistant API
api:

ota:
  password: "otapw"

time:
  - platform: homeassistant

wifi:
  ssid: "ssid"
  password: "pw"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Victron Fallback Hotspot"
    password: "password"

  use_address: "192.168.177.61"
captive_portal:
    

uart:
- id: uart_mppt
  tx_pin: D8  # Not connected! The communication is read-only
  rx_pin: D7  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

  
- id: uart_bmv
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  id: victron0
  uart_id: uart_mppt
  throttle: 10s

victron_smart_shunt:
  uart_id: uart_bmv

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${mpptname} max power yesterday"
    max_power_today:
      name: "${mpptname} max power today"
    yield_total:
      name: "${mpptname} yield total"
    yield_yesterday:
      name: "${mpptname} yield yesterday"
    yield_today:
      name: "${mpptname} yield today"
    panel_voltage:
      name: "${mpptname} panel voltage"
    panel_power:
      name: "${mpptname} panel power"
    battery_current:
      name: "${mpptname} battery current"
    battery_voltage:
      name: "${mpptname} battery voltage"
    day_number:
      name: "${mpptname} day number"
    charging_mode_id:
      name: "${mpptname} charging mode id"
    error_code:
      name: "${mpptname} error code"
    tracking_mode_id:
      name: "${mpptname} tracking mode id"
    load_current:
      name: "${mpptname} load current"


  - platform: victron_smart_shunt
    battery_voltage:
      name: "${bmvname} Battery Voltage"  
      id: bv

    battery_current:
      name: "${bmvname} Battery Current" 
      id: bc

    fw_version:
      name: "${bmvname} fw"  
      id: fw

    pid:
      name: "${bmvname} pid"  
      id: pid

    instanteneous_power:
      name: "${bmvname} instantaneous power"  
      id: instantaneous_power      

    time_to_go:
      name: "${bmvname} time to go"  
      id: time_to_go

    consumed_amp_hours:
      name: "${bmvname} consumed amp hours"
      id: consumed_amp_hours  
      unit_of_measurement: Ah

    min_battery_voltage:
      name: "${bmvname} Min battery voltage"
      id: min_battery_voltage   

    max_battery_voltage: 
      name: "${bmvname} Max battery voltage"
      id: max_battery_voltage     

    amount_of_charged:
      name: "${bmvname} Amount of charged"
      id:  amount_of_charged   
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh

    bmv_alarm_text:
      name: "${bmvname} alarm"
      id: bmv_alarm
      
    bmv_text:
      name: "${bmvname} pid"
      id: bmv_pid

    last_full_charge:
      name: "${bmvname} Time since last full charge"
      id: last_full_charge

    deepest_discharge:
      name: "${bmvname} Depth of the deepest discharge"
      id: deepest_discharge   
      unit_of_measurement: Ah

    last_discharge:
      name: "${bmvname} Depth of the last discharge"
      id: last_discharge
      unit_of_measurement: Ah

    discharged_energy:
      name: "${bmvname} Amount of discharged energy"
      id: discharged_energy   
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh

    state_of_charge:
      id: state_of_charge
      name: "${bmvname} SoC"  

text_sensor:
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "${mpptname} charging mode"
    error:
      name: "${mpptname} error"
    tracking_mode:
      name: "${mpptname} tracking mode"
    firmware_version:
      name: "${mpptname} firmware version"
    device_type:
      name: "${mpptname} device type"
    serial_number:
      name: "${mpptname} serial number"

binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "${mpptname} load state"
    relay_state:
      name: "${mpptname} relay state"
```

Thank you

**Comment by syssi** [comment]
Please try to avoid the second custom component:

```
  - source: github://KinDR007/VictronSmartShunt-ESPHOME@main
    refresh: 0s
```

The `victron` component supports both devices now. You have to instantiate the component multiple times:

```
uart:
  - id: uart0
    tx_pin: D8  # Not connected! The communication is read-only
    rx_pin: D7  # Connect this this GPIO and GND to the first MPPT charger
    baud_rate: 19200
    rx_buffer_size: 256
  - id: uart1
    tx_pin: D6  # Not connected! The communication is read-only
    rx_pin: D5  # Connect this this GPIO and GND to the second MPPT charger
    baud_rate: 19200
    rx_buffer_size: 256

victron:
  - id: victron0
    uart_id: uart0
    throttle: 10s
  - id: victron1
    uart_id: uart1
    throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${device0} max power yesterday"
    panel_voltage:
      name: "${device0} panel voltage"
    panel_power:
      name: "${device0} panel power"
    battery_current:
      name: "${device0} panel current"
    load_current:
      name: "${device0} load current"

  - platform: victron
    victron_id: victron1
    max_power_yesterday:
      name: "${device0} max power yesterday"
    panel_voltage:
      name: "${device1} panel voltage"
    panel_power:
      name: "${device1} panel power"
    battery_current:
      name: "${device1} panel current"
    load_current:
      name: "${device1} load current"
```
See https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartsolar-mppt-esp8266-example-multiple-uarts.yaml

In other words: You have to merge these examples to a single "multiple uart" configuration:

https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartshunt-esp8266-example.yaml
https://github.com/KinDR007/VictronMPPT-ESPHOME/blob/main/smartsolar-mppt-esp8266-example.yaml

In best case your issue is solved as soon the new configuration is in place. Please give it a try. In general multiple devices are possible without issues.
