### ISSUE TITLE
Some values are not displayed Victron MPPT 150/45 and 100/20

### ISSUE THREAD

**Issue by DerKlotz74** [KinDR007/VictronMPPT-ESPHOME#155]
Hello, 
I have the problem that some values are not supplied by the Victron. Please help. What is needed?

```
sensor:
  - platform: victron
    victron_id: victron150
    max_power_yesterday:
      name: "${device0} max power yesterday"
    max_power_today:
      name: "${device0} max power today"  
    panel_voltage:
      name: "${device0} panel voltage"
    panel_power:
      name: "${device0} panel power"
    battery_current:
      name: "${device0} panel current"
    load_current:
      name: "${device0} load current"
    battery_voltage:
      name: "${device0} battery voltage"
    min_battery_voltage:
      name: "${device0} min battery voltage" 
    max_battery_voltage:
      name: "${device0} max battery voltage" 
    number_of_charge_cycles:  
      name: "${device0} number of charge circles"
    number_of_full_discharges:
      name: "${device0} number of full discharges"
    amount_of_discharged_energy:
      name: "${device0} amount of discharged energy"
    amount_of_charged_energy:
      name: "${device0} amount of charged energy"  
```

![Victron1](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/18484044/2799f74a-d413-4b46-bc19-a87a0a353c9a)
![Victron2](https://github.com/KinDR007/VictronMPPT-ESPHOME/assets/18484044/7df00e28-c48c-4aa8-b7db-fb5d62b73cad)
