### ISSUE TITLE
battery_temperature not working

### ISSUE THREAD

**Issue by kkaminski7** [KinDR007/VictronMPPT-ESPHOME#99]
Hi
I have "Victron Smartsolar 100/20" mppt with "Smart battery sense" connected. Everything seems to work fine so far except "battery_temperature". Is it working?
Maybe I have defined it wrong in esphome, below my config for it:
```
    battery_temperature:
      name: "Battery Temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
```
